// web/src/app/activities/activity-preview/activity-preview.component.ts
import { Component, Input } from '@angular/core';

import { Activity } from '../activity';

@Component({
  selector: 'app-activity-preview',
  templateUrl: './activity-preview.component.html',
  styleUrls: ['./activity-preview.component.scss']
})
export class ActivityPreviewComponent {
  @Input() run: Activity;
}

<div *ngIf="run" class="activity__preview">
  
  <div class="header">
    <h3 class="date mb-0">{{ run?.startTime | date: "fullDate" }}</h3>
    <p class="title mb-0">{{ run?.title }}</p>
  </div>
  
  <img
    [src]="'data:image/png;base64,' + run?.image"
    alt="Activity GPS preview"
    class="map-image"
  />

  <div class="stats-footer">
    <div class="col">
      <p class="title">Distance</p>
      <p class="value mb-0">{{ run?.distance / 1000 | number: "1.2-2" }}km</p>
    </div>
    <div class="col">
      <p class="title">Pace</p>
      <p class="value mb-0">{{ run?.pace | pace }} min / km</p>
    </div>
    <div class="col">
      <p class="title">Elevation</p>
      <p class="value mb-0">{{ (run?.maxElevation - run?.minElevation) | number: "1.1-1" }} m</p>
    </div>
    <div class="col">
      <p class="title">Elapsed Time</p>
      <p class="value mb-0">{{ run?.elapsedTime | duration }}</p>
    </div>
  </div>
</div>

// web/src/Activities/ActivityPreview.tsx
import React from 'react';
import { useHistory } from 'react-router-dom';

import { format } from 'date-fns';

import { Activity } from './models';
import { Helpers } from '../Shared';
import '../styles/styles.scss'

type ActivityPreviewProps = {
  activity: Activity;
}

export const ActivityPreview = ({ activity }: ActivityPreviewProps) => {
  const history = useHistory();

  function openActivity() {
    history.push(`/activities/${activity.id}`);
  }

  function handleKeyDown(event: React.KeyboardEvent) {
    if (event.key === "ENTER") {
      openActivity()
    }
  }

  return (
    <div className="activity__preview focusable" tabIndex={0} onClick={openActivity} onKeyDown={handleKeyDown}>
      <div className="header">
        <h3 className="date mb-0">{ format(new Date(activity.startTime), "EEEE, LLLL d, yyyy") }</h3>
        <p className="title mb-0">{ activity.title }</p>
      </div>
      
      <img
        src={activity.image}
        alt="Activity GPS preview"
        className="map-image"
      />

      <div className="stats-footer">
        <FooterColumn title='Distance' value={ `${Number(activity.distance / 1000).toFixed(2)} km`} />
        <FooterColumn title='Pace' value={ `${Helpers.pace(activity.pace) } min / km`} />
        <FooterColumn title='Elevation' value={`${Number(activity.maxElevation - activity.minElevation).toFixed(1)} m`} />
        <FooterColumn title='Elapsed Time' value={ Helpers.duration(activity.elapsedTime)} />
      </div>
    </div>
  )
}

type FooterColumnProps = {
  title: string;
  value: string;
}

const FooterColumn = ({title, value}: FooterColumnProps) => {
  return (
    <div className="col">
      <p className="title">{ title }</p>
      <p className="value mb-0">{ value }</p>
    </div>
  )
}
