// web/src/Shared/Loading.tsx
import React from 'react';
import '../styles/styles.scss'

export const Loading = () => {
  return (
    <div className="container">
      <div className="spinner-grow text-warning" role="status"></div>
      <div className="spinner-grow text-success" role="status"></div>
      <div className="spinner-grow text-info" role="status"></div>
    </div>
  )
}

// web/src/app/shared/loading/loading.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-loading',
  template: `
  <div class="container">
    <div class="spinner-grow text-warning" role="status">
      <span class="sr-only">Loading...</span>
    </div>
    <div class="spinner-grow text-success" role="status">
      <span class="sr-only">Loading...</span>
    </div>
    <div class="spinner-grow text-info" role="status">
      <span class="sr-only">Loading...</span>
    </div>
  </div>`,
  styleUrls: ['./loading.component.scss']
})
export class LoadingComponent {}
