// web-react/src/Activities/ActivityList.tsx
import React, { useEffect, useState, ChangeEvent } from 'react';
import { useHistory } from 'react-router-dom';

import { ReactComponent as CloudIcon } from 'bootstrap-icons/icons/cloud-upload.svg';
import InfiniteScroll from 'react-infinite-scroll-component';

import { ActivityPreview } from './ActivityPreview';
import { ActivityService } from './ActivityService';

import { Activity, ActivityTypeAggregation } from './models';
import { Loading } from '../Shared';

export const ActivityList = () => {
  const history = useHistory()
  const [activities, setActivities] = useState<Array<Activity>>([]);
  const [totalCount, setTotalCount] = useState(0);
  const [page, setPage] = useState(1);
  const [filters, setFilters] = useState<Array<ActivityTypeAggregation>>([]);

  useEffect(() => {
    getActivities(page, null).then(resp => {
      updateActivities(resp.data.results, resp.data.totalCount)
    })

    ActivityService.getFilters().then(resp => {
      setFilters(resp.data);
    })
  }, []);

  function updateActivities(activities: Activity[], count: number) {
    setTotalCount(count);
    setActivities(activities);
  }

  function getActivities(pageNumber: number = 1, filter: string | null) {
    return ActivityService.getAllActivities(pageNumber, 3, filter);
  }

  function handleFilterChange(event: ChangeEvent<HTMLSelectElement>) {
    const filter = event.target.value;
  }

  function loadNext() {
    getActivities(page + 1, null).then(resp => {
      updateActivities([
        ...activities,
        ...resp.data.results
      ], resp.data.totalCount);
      setPage(page + 1);
    })
  }

  function onUploadClick() {
    history.push('/activities/upload')
  }

  return (
    <div className="activity__list-wrapper">
      <div className="activity__list">
        <div className="options">
          <button
            type="button"
            className="btn btn-outline-secondary upload-btn"
            onClick={onUploadClick}
          >Upload <CloudIcon />
          </button>
          {/* <select
            className="form-select type-filters"
            aria-label="Default select example"
            onChange={handleFilterChange}
          >
            <option value='All'>Filter by: All</option>
            { filters && filters.map(filter => (
              <option key={filter.Name} value={filter.Name}>{ filter.Name } ({filter.Total})</option>
            ))}
          </select> */}
        </div>
        <InfiniteScroll
          dataLength={activities.length}
          next={loadNext}
          hasMore={activities.length < totalCount}
          loader={<Loading />}
        >
          { activities.map(activity => (
            <ActivityPreview 
              key={activity.id}
              activity={activity}
            />
          ))}
        </InfiniteScroll>
      </div>
    </div>
  )
}

// web/src/app/activities/activity-list/activity-list.component.ts
// Core Imports
import { Component, OnInit, OnDestroy } from '@angular/core';
import { DataSource, CollectionViewer } from '@angular/cdk/collections';

// Third Party Imports
import { BehaviorSubject, Subscription, Observable } from 'rxjs';
import { SubSink } from 'subsink';

// App Imports
import { ActivityService } from '../activity.service';
import { Activity, ActivityTypeAggregation } from '../activity';
import { Router } from '@angular/router';

@Component({
  selector: 'app-activity-list',
  templateUrl: './activity-list.component.html',
  styleUrls: ['./activity-list.component.scss']
})
export class ActivityListComponent implements OnInit, OnDestroy {
  private subs = new SubSink();

  dataSource: ActivityDataSource;
  filters: ActivityTypeAggregation[];

  constructor(
    private activityService: ActivityService,
    private router: Router
  ) {
    this.dataSource = new ActivityDataSource(activityService);
  }

  onChange(value: string): void {
    this.dataSource.filterType = value;
  }

  ngOnInit(): void {
    this.subs.sink = this.activityService.getFilters().subscribe(resp => {
      this.filters = resp;
    });
  }

  onActivityClick(activity: Activity): void {
    this.router.navigate(['/activities', activity.id]);
  }

  /**
   * Used by cdkVirtuaFor to track elements rendered on the screen.
   */
  trackById(index: number, activity: Activity): string {
    return activity.id;
  }

  ngOnDestroy(): void {
    this.subs.unsubscribe();
  }
}

/**
 * ActivityDataSource implements the DataSource interface used by the cdk-virtual-scroll-viewport
 * element within ActivityPreviewComponent.
 *
 * It is used to automatically load new data as the page scrolls.
 */
class ActivityDataSource extends DataSource<Activity | undefined> {
  private cachedActivities = Array.from<Activity>({ length: 0 });
  private dataStream = new BehaviorSubject<(Activity | undefined)[]>(this.cachedActivities);
  private subscription = new Subscription();

  private pageSize = 4;
  private lastPage = 0;
  private typeFilter = '';

  isLoading = false;

  set filterType(v: string) {
    this.typeFilter = v;
    this.cachedActivities = [];
    this.dataStream.next([]);
    this.fetchPage(1);
  }

  constructor(private activityService: ActivityService) {
    super();

    this.fetchPage(1);
  }

  connect(collectionViewer: CollectionViewer): Observable<(Activity | undefined)[] | ReadonlyArray<Activity | undefined>> {
    this.subscription.add(collectionViewer.viewChange.subscribe(range => {
      const currentPage = Math.floor(range.end / this.pageSize);

      if (currentPage > this.lastPage) {
        this.lastPage = currentPage;
        this.fetchPage(currentPage + 1);
      }
    }));

    return this.dataStream;
  }

  disconnect(collectionViewer: CollectionViewer): void {
    this.subscription.unsubscribe();
  }

  private fetchPage(pageNumber: number): void {
    this.isLoading = true;
    this.activityService.getAllRuns(pageNumber, this.pageSize, this.typeFilter).subscribe(resp => {
      this.cachedActivities = this.cachedActivities.concat(resp.results);
      this.dataStream.next(this.cachedActivities);
      this.isLoading = false;
    });
  }
}

<cdk-virtual-scroll-viewport [itemSize]="450" class="scroll-viewport">
  <div class="activity__list-wrapper">
    <div class="activity__list">
      <div class="options">
        <button
          type="button"
          class="btn btn-outline-secondary upload-btn"
          [routerLink]="'/upload'"
          [disabled]="dataSource.isLoading ? true : null"
        >Upload
          <img src="assets/img/cloud-upload.svg" alt="Upload new activity" title="Upload">
        </button>
        <select class="form-select type-filters" aria-label="Default select example" (change)="onChange($event.target.value)">
          <option selected value=''>Filter by: All</option>
          <ng-container *ngFor="let filter of filters">
            <option [value]="filter.Name">{{ filter.Name }} ({{ filter.Total }})</option>
          </ng-container>
        </select>
      </div>
      <ng-container *cdkVirtualFor="let run of dataSource; trackBy: trackById">
        <app-activity-preview *ngIf="run" [run]="run" (activityClick)="onActivityClick(run)"></app-activity-preview>
      </ng-container>
    </div>
  </div>
  <ng-container *ngIf="dataSource.isLoading">
    <app-loading></app-loading>
  </ng-container>
</cdk-virtual-scroll-viewport>
