// web/src/app/activities/activity-preview/activity-preview.component.ts
import { Component, Input } from '@angular/core';

import { Activity } from '../activity';

@Component({
  selector: 'app-activity-preview',
  templateUrl: './activity-preview.component.html',
  styleUrls: ['./activity-preview.component.scss']
})
export class ActivityPreviewComponent {
  @Input() run: Activity;
}

<div *ngIf="run" class="activity__preview">
  
  <div class="header">
    <h3 class="date mb-0">{{ run?.startTime | date: "fullDate" }}</h3>
    <p class="title mb-0">{{ run?.title }}</p>
  </div>
  
  <img
    [src]="'data:image/png;base64,' + run?.image"
    alt="Activity GPS preview"
    class="map-image"
  />

  <div class="stats-footer">
    <div class="col">
      <p class="title">Distance</p>
      <p class="value mb-0">{{ run?.distance / 1000 | number: "1.2-2" }}km</p>
    </div>
    <div class="col">
      <p class="title">Pace</p>
      <p class="value mb-0">{{ run?.pace | pace }} min / km</p>
    </div>
    <div class="col">
      <p class="title">Elevation</p>
      <p class="value mb-0">{{ (run?.maxElevation - run?.minElevation) | number: "1.1-1" }} m</p>
    </div>
    <div class="col">
      <p class="title">Elapsed Time</p>
      <p class="value mb-0">{{ run?.elapsedTime | duration }}</p>
    </div>
  </div>
</div>

// web-react/src/Activities/ActivityPreview.tsx
import React from 'react';

import { Activity } from './models';
import { Pipes } from './pipes';
import '../styles/styles.scss'

type ActivityPreviewProps = {
  activity: Activity;
}

export const ActivityPreview = ({ activity }: ActivityPreviewProps) => {
  const openActivity = () => {
    console.log('open');
  }

  return (
    <div className="activity__preview" onClick={openActivity}>
      <div className="header">
        <h3 className="date mb-0">{ activity.startTime.toDateString() }</h3>
        <p className="title mb-0">{ activity.title }</p>
      </div>
      
      <img
        src={'data:image/png;base64,' + activity.image}
        alt="Activity GPS preview"
        className="map-image"
      />

      <div className="stats-footer">
        <div className="col">
          <p className="title">Distance</p>
          <p className="value mb-0">{ Number(activity.distance / 1000).toFixed(2) }km</p>
        </div>
        <div className="col">
          <p className="title">Pace</p>
          <p className="value mb-0">{ Pipes.pace(activity.pace) } min / km</p>
        </div>
        <div className="col">
          <p className="title">Elevation</p>
          <p className="value mb-0">{ (activity.maxElevation - activity.minElevation) } m</p>
        </div>
        <div className="col">
          <p className="title">Elapsed Time</p>
          <p className="value mb-0">{ Pipes.duration(activity.elapsedTime) }</p>
        </div>
      </div>
    </div>
  )
}
