// web/src/app/activities/detailed-activity/detailed-activity.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { SubSink } from 'subsink';

import { ActivityService } from '../activity.service';
import { Activity, Point } from '../activity';

@Component({
  selector: 'app-detailed-activity',
  templateUrl: './detailed-activity.component.html',
  styleUrls: ['./detailed-activity.component.scss']
})
export class DetailedActivityComponent implements OnInit {
  private id: string;
  private subs = new SubSink();

  loading = true;
  activity: Activity;

  // Chart data
  // TODO(me): Separate/common component
  elevationData: any[] = [];
  paceData: any[] = [];
  splitsData: any[] = [];

  // Chart optiosn
  legend = false;
  showLabels = true;
  animations = true;
  xAxis = true;
  yAxis = true;
  showYAxisLabel = true;
  showXAxisLabel = true;
  xAxisLabel = 'Distance';
  yAxisLabel = 'Elevation';
  timeline = true;
  yScaleMin = Number.MAX_SAFE_INTEGER;
  yScaleMaxPace = 3;

  colorScheme = {
    domain: ['#5AA454', '#E44D25', '#CFC0BB', '#7aa3e5', '#a8385d', '#aae3f5']
  };

  colorSchemePace = {
    domain: ['']
  };

  colorSchemeSplits = {
    domain: ['#4baeeb']
  }

  constructor(
    private route: ActivatedRoute,
    private activityService: ActivityService
  ) {}

  ngOnInit(): void {
    this.id = this.route.snapshot.paramMap.get('id');

    this.subs.sink = this.activityService.getRun(this.id).subscribe(resp => {
      this.activity = resp;
      this.loading = false;
    });

    this.subs.sink = this.activityService.getPoints(this.id).subscribe(resp => {
      this.processPoints(resp.points);
    });
  }

  formatXAxis(v: any): string {
    return `${Number(v).toFixed(1)} km`;
  }

  formatYAxis(v: any): string {
    return `${v} m`;
  }

  formatPce(metersPerSec: any): string {
    if (metersPerSec === 0) {
      return `0`;
    }

    const secondsPerKm = 1000 / metersPerSec;

    const minutes = Math.floor(secondsPerKm / 60);
    const seconds = secondsPerKm - (minutes * 60);
    return `${minutes}:${Number(seconds).toFixed(0).padStart(2, '0' )} / km`;
  }

  metresPerSecondToMinutesPerKm(metersPerSec: number): number {
    if (metersPerSec === 0) {
      return 0;
    }

    const secondsPerKm = 1000 / metersPerSec;

    return secondsPerKm / 60;
  }

  private processPoints(points: Point[]): void {
    const data = [];
    const paces = [];

    points.forEach((point, i) => {
      data.push({
        // TODO: Maybe be better to label with time
        name: `${point.distanceFromStart / 1000}`,
        value: point.elevation
      });

      paces.push({
        name: `${point.distanceFromStart / 1000}`,
        value: point.pace
      });

      if (point.elevation < this.yScaleMin) {
        this.yScaleMin = point.elevation - 2;
      }
    });

    this.elevationData = [
      {
        name: `Elevations`,
        series: data
      }
    ];

    this.paceData = [
      {
        name: 'Pace',
        series: paces
      }
    ];

    this.splitsData = this.buildSplits(points);
  }

  private buildSplits(points: Point[]): any[] {
    const data = [];

    let currentSplit = 1; // 1st KM
    let startTime = points[0].time;

    points.forEach((point, index) => {
      if (point.distanceFromStart < (currentSplit * 1000)) {
        return;
      }

      const seconds = (new Date(point.time).getTime() - new Date(startTime).getTime()) / 1000;

      data.push({
        name: `${currentSplit}km`,
        value: 1000 / seconds
      });
      currentSplit++;
      startTime = point.time;
    });

    const lastPoint = points[points.length - 1];
    const seconds = (new Date(lastPoint.time).getTime() - new Date(startTime).getTime()) / 1000;

    const dist = lastPoint.distanceFromStart - (1000 * (currentSplit - 1));

    // If the last split is less than 100m, ignore it
    if (dist < 100) {
      return data;
    }

    data.push({
      name: `${currentSplit}km`,
      value: seconds / dist
    });


    return data;
  }
}

<div class="activity-component">
  <div class="header">
    <button type="button" class="btn btn-outline-dark btn-sm" [routerLink]="'/activities'"><img src="assets/img/chevron-left.svg"> Activities</button>
    <h4 class="activity-type mb-0">{{ activity?.type ? activity.type : 'Loading' }}</h4>
  </div>
  
  <div *ngIf="activity; else showLoading" class="detail-activity">
    <p class="lead">{{ activity.startTime | date: 'HH:mm'}} on {{ activity.startTime | date: 'EEEE, MMMM d, y' }}</p>
    <app-mapbox-map
    [activity]="activity"
    ></app-mapbox-map>
    <h3 class="el-text mt-3">Elevation</h3>
    
    <div class="elevation-profile profile" *ngIf="elevationData.length > 0">
      <!-- TODO(me): How to reduce xAxis ticks to per/km??  -->
      <ngx-charts-area-chart
        [animations]="false"
        [scheme]="colorScheme"
        [legend]="legend"
        [showXAxisLabel]="false"
        [showYAxisLabel]="false"
        [xAxis]="xAxis"
        [yAxis]="yAxis"
        [xAxisLabel]="xAxisLabel"
        [yAxisLabel]="yAxisLabel"
        [timeline]="timeline"
        [results]="elevationData"
        [yScaleMin]="yScaleMin"
        [showGridLines]="false"
        [xAxisTickFormatting]="formatXAxis"
        [yAxisTickFormatting]="formatYAxis"
      ></ngx-charts-area-chart>  
    </div>

    <h3 class="el-text mt-3">Pace</h3>
    <div class="pace-profile profile" *ngIf="paceData.length > 0">
      <!-- TODO(me): How to reduce xAxis ticks to per/km??  -->
      <ngx-charts-area-chart
        [animations]="false"
        [scheme]="colorSchemePace"
        [legend]="legend"
        [showXAxisLabel]="false"
        [xAxis]="xAxis"
        [yAxis]="false"
        [xAxisLabel]="xAxisLabel"
        [timeline]="timeline"
        [results]="paceData"
        [showGridLines]="false"
        [xAxisTickFormatting]="formatXAxis"
      ></ngx-charts-area-chart>  
    </div>

    <h3 class="el-text mt-3">Splits</h3>
    <div class="splits-profile profile" *ngIf="splitsData.length > 0">
      <ngx-charts-bar-vertical
        [animations]="false"
        [scheme]="colorSchemeSplits"
        [legend]="legend"
        [showXAxisLabel]="false"
        [xAxis]="xAxis"
        [yAxis]="true"
        [yScaleMax]="yScaleMaxPace"
        [xAxisLabel]="xAxisLabel"
        [results]="splitsData"
        [showGridLines]="false"
        [yAxisTickFormatting]="formatPce"
      >
      </ngx-charts-bar-vertical>
    </div>
  </div>
  <ng-template #showLoading>
    <div class="loading">
      <app-loading></app-loading>
    </div>
  </ng-template>
</div>

// web-react/src/Activities/DetailedActivity.tsx
import React, { useEffect, useState } from 'react';
import { useParams, useHistory } from 'react-router-dom';

import {
  ReactComponent as ChevronLeft
} from 'bootstrap-icons/icons/chevron-left.svg';
import { format } from 'date-fns';
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  BarChart,
  Bar
} from "recharts";

import { Mapbox } from '../Shared';
import { ActivityService } from './ActivityService';
import { Activity, PointResponse, Point } from './models';
import { Loading } from '../Shared';

export const DetailedActivity = () => {
  const history = useHistory();
  const { activityId } = useParams();

  const [ activity, setActivity ] = useState<Activity>();
  const [ elevationData, setElevationData ] = useState<object[]>();
  const [ paceData, setPaceData ] = useState<object[]>();
  const [ splitsData, setSplitsData ] = useState<object[]>();

  useEffect(() => {
    ActivityService
      .getActivity(activityId)
      .then(response => {
        setActivity(response.data)
      });
  }, [ activityId ]);

  useEffect(() => {
    ActivityService.getPoints(activityId)
      .then(response => {
        processPoints(response.data)
      })
  }, [activityId]);

  function processPoints(points: PointResponse) {
    const elevationData: object[] = [];
    const paceData: object[] = [];

    points.points.forEach((point, i) => {
      if (i % 5 !== 0) {
        return;
      }

      elevationData.push({
        // TODO: Maybe be better to label with time
        distance: Number(point.distanceFromStart / 1000).toFixed(1),
        elevation: Number(point.elevation).toFixed(1)
      });

      paceData.push({
        distance: Number(point.distanceFromStart / 1000).toFixed(1),
        pace: Number(point.pace).toFixed(2)
      });

    });
    
    const splitsData = buildSplits(points.points);

    setElevationData(elevationData);
    setPaceData(paceData);
    setSplitsData(splitsData);
  }

  function buildSplits(points: Point[]): any[] {
    const data: object[] = [];

    let currentSplit = 1; // 1st KM
    let startTime = points[0].time;

    points.forEach((point, i) => {
      if (point.distanceFromStart < (currentSplit * 1000)) {
        return;
      }

      const seconds = (new Date(point.time).getTime() - new Date(startTime).getTime()) / 1000;

      data.push({
        name: currentSplit,
        value: Number(1000 / seconds).toFixed(4)
      });
      currentSplit++;
      startTime = point.time;
    });

    const lastPoint = points[points.length - 1];
    const seconds = (new Date(lastPoint.time).getTime() - new Date(startTime).getTime()) / 1000;

    const dist = lastPoint.distanceFromStart - (1000 * (currentSplit - 1));

    // If the last split is less than 100m, ignore it
    if (dist < 100) {
      return data;
    }

    data.push({
      name: currentSplit,
      value: Number(seconds / dist).toFixed(2)
    });


    return data;
  }

  function goBack() {
    history.goBack();
  }
  
  return (
    <div className="activity-component">
      <div className="header-detail">
        <button type="button" className="btn btn-outline-dark btn-sm" onClick={goBack}><ChevronLeft /> Activities</button>
        <h4 className="activity-type mb-0">{ activity?.type ? activity.type : 'Loading' }</h4>
      </div>
       
      { activity ? (
        <div className="detail-activity">
          <p className="lead">{ `${format(new Date(activity.startTime), 'HH:mm')} on ${format(new Date(activity.startTime), 'EEEE, LLLL d, yyyy')}`}</p>
          <Mapbox bounds={ activity.bounds } polyline={ activity.polyline } />

          <h3 className="el-text mt-3">Elevation</h3>
          <ResponsiveContainer height={250} width='100%'>
            <AreaChart
              data={elevationData}
              margin={{
                top: 10, right: 30, left: 0, bottom: 0,
              }}
            >
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="distance" allowDecimals={false} tickCount={4} unit={'km'} minTickGap={20} />
              <YAxis allowDecimals={false} unit={'m'} />
              <Tooltip />
              <Area isAnimationActive={false} type="monotone" dataKey="elevation" stroke="#8884d8" fill="#8884d8" />
            </AreaChart>
          </ResponsiveContainer>
          
          <h3 className="el-text mt-3">Pace</h3>
          <ResponsiveContainer height={250} width='100%'>
            <AreaChart
              data={paceData}
              margin={{
                top: 10, right: 30, left: 0, bottom: 0,
              }}
            >
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="distance" allowDecimals={false} tickCount={4} unit={'km'} minTickGap={20} />
              <YAxis allowDecimals={false} unit={'m/s'} />
              <Tooltip />
              <Area isAnimationActive={false} type="monotone" dataKey="pace" stroke="#5293fa" fill="#5293fa" />
            </AreaChart>
          </ResponsiveContainer>

          <h3 className="el-text mt-3">Splits</h3>
          <ResponsiveContainer height={250} width='100%'>
            <BarChart data={splitsData} >
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="name" />
              <YAxis />
              <Tooltip />
              <Bar dataKey="value" fill="#6fd450" />
            </BarChart>
          </ResponsiveContainer>
        </div>
      ) : <Loading />}
    </div>
  )
}
